#!/bin/sh

RELEASE_VERSION=$1
NEXT_VERSION=$2

if [[ -z $RELEASE_VERSION ]] || [[ -z $NEXT_VERSION ]]
then
  echo "Must provide both release version and next version"
  exit 1
fi

mvn clean versions:set -DnewVersion=$RELEASE_VERSION
mvn deploy scm:tag
mvn clean versions:set -DnewVersion=$NEXT_VERSION
git commit -am "Update version to $NEXT_VERSION after release of $RELEASE_VERSION"
